root: true
env:
  node: true
  es2021: true
  mocha: true
extends:
  - 'airbnb-base'
  - 'airbnb-typescript/base'
  - 'eslint:recommended'
  - 'plugin:promise/recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - promise
  - '@typescript-eslint'
rules:
  import/prefer-default-export: 0
  implicit-arrow-linebreak: 0
  max-len: ['error', { 'code': 120 }]
  no-param-reassign: 0
  '@typescript-eslint/no-non-null-assertion': 0
settings:
  import/parsers:
    '@typescript-eslint/parser': ['.ts', '.tsx']
  import/resolver:
    node:
      extensions:
        # if unset, default is just ".js", but it must be re-added explicitly if set
        - .js
        - .jsx
        - .ts
        - .tsx
    typescript:
      alwaysTryTypes: false
overrides:
  - files: ['*.spec.ts']
    rules:
      '@typescript-eslint/no-unused-expressions': 0
      '@typescript-eslint/no-unsafe-return': 0
      '@typescript-eslint/no-unsafe-assignment': 0
      class-methods-use-this: 0
  - files: ['*.entity.ts']
    rules:
      import/no-cycle: 0
