name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn run build

      - name: Run unit tests
        run: yarn run test
