name: Version bump

concurrency: one-at-a-time

on:
  push:
    branches:
      - master

jobs:
  standard-version:
    name: Bump package version with standard-version
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # gives standard-version access to all previous commits

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: generate tag and release body
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          yarn release 
          yarn dlx extract-changelog-release > RELEASE_BODY.md

      - name: publish tag
        id: publish_tag
        run: |
          git push --follow-tags
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md
